[workspace]
members = [
    "stcp_core",
    "the_rust_implementation"
]

resolver = "2"

#[workspace.dependencies]
#stcp_core = { path = "stcp_core",  default-features = false  }
#the_rust_implementation = { path = "the_rust_implementation", default-features = false }
